In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
url = "https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv"

df = pd.read_csv(url)

print(df.shape)
df.head()

(23195, 130)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [ ]:
## Filter data only using World
df = df[df['country'] == 'World']
## The data that are chosen are from 1960
df = df[df['year'] >= 1990]
df.shape

(35, 130)

In [ ]:
list_columns = df.columns.tolist()
list_columns

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_demand_per_capita',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

In [ ]:
cols = [
    "year", "primary_energy_consumption", "fossil_fuel_consumption", "renewables_consumption",
    "coal_consumption", "oil_consumption", "gas_consumption", "low_carbon_consumption", "nuclear_consumption",
    "coal_share_energy", "fossil_share_energy", "gas_share_energy", "low_carbon_share_energy", "nuclear_share_energy",
    "oil_share_energy", "renewables_share_energy",
]

df = df[cols].reset_index(drop=True)
df

,year,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,coal_consumption,oil_consumption,gas_consumption,low_carbon_consumption,nuclear_consumption,coal_share_energy,fossil_share_energy,gas_share_energy,low_carbon_share_energy,nuclear_share_energy,oil_share_energy,renewables_share_energy
0,1990,95856.289,83316.875,6480.236,25928.912,37906.816,19481.150,12037.447,5557.211,27.192,87.376,20.430,12.624,5.828,39.754,6.796
1,1991,96516.406,83536.398,6640.318,25686.727,37876.832,19972.838,12463.400,5823.083,26.757,87.017,20.805,12.983,6.066,39.455,6.917
2,1992,97104.883,84052.555,6667.230,25584.301,38404.773,20063.482,12534.516,5867.286,26.488,87.023,20.772,12.977,6.075,39.762,6.903
3,1993,97894.812,84220.555,7058.777,25708.832,38246.242,20265.482,13128.123,6069.346,26.409,86.514,20.817,13.486,6.235,39.288,7.251
4,1994,99137.250,85272.977,7129.369,25815.188,39068.176,20389.613,13312.643,6183.274,26.186,86.496,20.682,13.504,6.272,39.629,7.232
5,1995,101315.359,86770.078,7512.383,25999.217,39666.371,21104.492,13963.854,6451.471,25.810,86.138,20.951,13.862,6.404,39.377,7.458
6,1996,104245.836,89353.367,7615.427,26617.482,40576.629,22159.254,14300.469,6685.042,25.679,86.204,21.378,13.796,6.449,39.146,7.347
7,1997,105269.266,90245.734,7784.813,26563.252,41652.086,22030.393,14423.880,6639.067,25.378,86.220,21.048,13.780,6.343,39.794,7.438
8,1998,105852.398,90618.578,7874.825,26395.965,41788.617,22434.000,14628.145,6753.319,25.080,86.101,21.316,13.899,6.417,39.705,7.482
9,1999,107613.984,92016.500,7972.275,26508.807,42435.785,23071.904,14982.567,7010.293,24.775,85.997,21.563,14.003,6.552,39.660,7.451
10,2000,110416.398,94467.258,8152.467,27456.373,43016.629,23994.258,15320.988,7168.521,25.008,86.045,21.855,13.955,6.529,39.181,7.426
11,2001,111493.289,95595.227,7964.840,27880.072,43398.320,24316.832,15295.052,7330.212,25.142,86.207,21.929,13.793,6.610,39.136,7.183
12,2002,113894.430,97731.234,8138.824,28982.217,43697.090,25051.928,15524.974,7386.150,25.590,86.292,22.120,13.708,6.522,38.583,7.186
13,2003,117849.602,101858.211,8177.063,31519.594,44610.883,25727.734,15374.122,7197.059,26.886,86.886,21.946,13.114,6.139,38.053,6.975
14,2004,123841.742,106903.773,8811.904,33708.973,46413.184,26781.619,16295.263,7483.358,27.361,86.773,21.738,13.227,6.074,37.673,7.153
15,2005,127936.719,110657.062,9151.290,36200.953,47016.887,27439.225,16593.777,7442.488,28.448,86.960,21.563,13.040,5.849,36.948,7.192
16,2006,131481.203,113695.703,9598.000,38087.039,47436.953,28171.709,17092.947,7494.948,29.121,86.931,21.540,13.069,5.731,36.270,7.339
17,2007,135617.984,117667.508,9962.659,40241.703,48087.520,29338.285,17265.766,7303.106,29.823,87.204,21.743,12.796,5.412,35.638,7.383
18,2008,137229.406,118540.047,10720.294,40796.645,47692.652,30050.746,17943.129,7222.835,29.891,86.853,22.018,13.147,5.292,34.944,7.855
19,2009,135033.219,116256.578,10959.966,40219.008,46633.969,29403.605,18043.217,7083.252,29.947,86.565,21.894,13.435,5.274,34.724,8.161
20,2010,141602.047,121801.430,11784.370,42016.016,48192.543,31592.871,18993.393,7209.022,29.842,86.510,22.439,13.490,5.120,34.229,8.370
21,2011,144913.297,124911.508,12318.797,43983.352,48578.273,32349.885,19190.367,6871.570,30.522,86.683,22.449,13.317,4.769,33.711,8.549
22,2012,147002.422,126707.328,13101.090,44098.684,49362.211,33246.438,19468.467,6367.377,30.168,86.681,22.744,13.319,4.356,33.769,8.963
23,2013,149599.734,128401.547,13929.002,44745.465,49922.812,33733.266,20297.982,6368.981,30.091,86.350,22.686,13.650,4.283,33.573,9.367
24,2014,151239.172,129225.125,14629.965,44912.371,50336.395,33976.355,21095.932,6465.966,29.878,85.966,22.603,14.034,4.301,33.486,9.732
25,2015,152357.625,129769.422,15143.938,43695.344,51294.031,34780.043,21663.787,6519.850,28.855,85.694,22.967,14.306,4.305,33.872,10.000
26,2016,154221.484,130666.328,15981.749,42767.824,52314.516,35583.984,22548.725,6566.976,27.914,85.283,23.225,14.717,4.286,34.145,10.431
27,2017,157625.312,133092.719,16900.693,43226.340,53263.332,36603.055,23493.197,6592.505,27.606,84.997,23.376,15.003,4.210,34.015,10.793
28,2018,161806.125,136007.172,18004.244,43897.328,53792.789,38317.059,24721.221,6716.976,27.311,84.619,23.840,15.381,4.179,33.468,11.202
29,2019,163694.609,136678.062,18936.256,43627.613,53997.266,39053.180,25856.449,6920.192,26.842,84.092,24.028,15.908,4.258,33.222,11.651
30,2020,157993.891,130121.617,20040.709,42316.324,49101.246,38704.047,26680.227,6639.518,26.987,82.985,24.683,17.015,4.234,31.314,12.781
31,2021,166043.500,136714.719,21197.068,44642.164,51846.820,40225.734,28100.395,6903.327,27.086,82.950,24.407,17.050,4.189,31.458,12.861
32,2022,169061.531,138548.688,22657.553,44926.926,53562.109,40059.652,29240.883,6583.331,26.776,82.573,23.875,17.427,3.924,31.922,13.504
33,2023,172238.781,140308.984,23814.445,45319.086,54838.684,40151.219,30491.574,6677.130,26.533,82.148,23.508,17.852,3.909,32.107,13.943
34,2024,176737.094,142420.891,25979.023,45850.543,55292.082,41278.270,32850.859,6871.835,26.160,81.257,23.551,18.743,3.921,31.546,14.822

In [ ]:
df['renewables_yoy_growth_pct'] = df['renewables_consumption'].pct_change() * 100
df['primary_energy_yoy_growth_pct'] = df['primary_energy_consumption'].pct_change() * 100

In [ ]:
df.head()

,year,primary_energy_consumption,fossil_fuel_consumption,renewables_consumption,coal_consumption,oil_consumption,gas_consumption,low_carbon_consumption,nuclear_consumption,coal_share_energy,fossil_share_energy,gas_share_energy,low_carbon_share_energy,nuclear_share_energy,oil_share_energy,renewables_share_energy,renewables_yoy_growth_pct,primary_energy_yoy_growth_pct
0,1990,95856.289,83316.875,6480.236,25928.912,37906.816,19481.150,12037.447,5557.211,27.192,87.376,20.430,12.624,5.828,39.754,6.796,NaN,NaN
1,1991,96516.406,83536.398,6640.318,25686.727,37876.832,19972.838,12463.400,5823.083,26.757,87.017,20.805,12.983,6.066,39.455,6.917,2.470311,0.688653
2,1992,97104.883,84052.555,6667.230,25584.301,38404.773,20063.482,12534.516,5867.286,26.488,87.023,20.772,12.977,6.075,39.762,6.903,0.405282,0.609717
3,1993,97894.812,84220.555,7058.777,25708.832,38246.242,20265.482,13128.123,6069.346,26.409,86.514,20.817,13.486,6.235,39.288,7.251,5.872709,0.813480
4,1994,99137.250,85272.977,7129.369,25815.188,39068.176,20389.613,13312.643,6183.274,26.186,86.496,20.682,13.504,6.272,39.629,7.232,1.000060,1.269156

In [ ]:
df.to_csv("world_consumption_energy.csv")